name: CodeCeption

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    types: [ opened, labeled, synchronize ]

jobs:
  build-test:
    if: contains(github.event.pull_request.labels.*.name, 'run analysis')
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - php: 8.2
            wordpress: master
          - php: 8.0
            wordpress: 5.8
    name: PHP ${{ matrix.php }} tests in WP ${{ matrix.wordpress }}
    steps:
      - uses: actions/checkout@v3.5.0

      # get the PHP version
      - uses: shivammathur/setup-php@2.24.0
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit-polyfills
      - run: composer install --no-progress --ansi

      - name: Installing WordPress
        run: |
          export WP_DEVELOP_DIR=/tmp/wordpress/
          git clone --depth=50 --branch="${{ matrix.wordpress }}" git://develop.git.wordpress.org/ /tmp/wordpress
          cd ..
          cp -r "${GITHUB_REPOSITORY#*/}" "/tmp/wordpress/src/wp-content/plugins/${GITHUB_REPOSITORY#*/}"
          cd /tmp/wordpress/
          pwd
          cp wp-tests-config-sample.php wp-tests-config.php
          sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
          sed -i "s/yourusernamehere/root/" wp-tests-config.php
          sed -i "s/yourpasswordhere/root/" wp-tests-config.php
      - name: Creating database
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -proot -e "CREATE DATABASE wordpress_tests;"
      - name: Check Syntax
        run: find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
      - name: Run chromedriver
        run:  nohup $CHROMEWEBDRIVER/chromedriver --url-base=/wd/hub /dev/null 2>&1 &
      - name: Codeception tests
        run: |
          cd "/tmp/wordpress/src/wp-content/plugins/${GITHUB_REPOSITORY#*/}"
          pwd
          php vendor/bin/codecept run wpunit
