name: "Pagely Deploy"
on:
  # Trigger the workflow on push only for the main branch
  pull_request:
    types: [ opened, labeled, synchronize ]

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'beta release')
    name: Deploy to Pagely
    runs-on: ubuntu-latest
    env:
      DESTINATION: "/httpdocs/wp-content/plugins/business-directory-plugin-${{ github.event.number }}"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run deploy to Formidable sandbox
        uses: pagely/action-deploy@v1
        with:
          PAGELY_DEPLOY_DEST: ${{env.DESTINATION}}
          PAGELY_INTEGRATION_SECRET: ${{secrets.PAGELY_SANDBOX_SECRET}}
          PAGELY_INTEGRATION_ID: "syDhbcpUFP6qGNYgQ7YoLe"
          PAGELY_APP_ID: "12009"
          PAGELY_WORKING_DIR: "${{github.workspace}}"
